services:
  db:
    image: postgres:15
    network_mode: host
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      network: host
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_NAME: tasksdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    network_mode: host
    ports:
      - "80:80"
    depends_on:
      - backend

  node-exporter:
    image: prom/node-exporter:latest
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pgdata:
  prometheus_data:
  grafana_data: