version: "3.9"

services:
  db:
    image: postgres:15
    network_mode: host
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_NAME: tasksdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  pgdata: